/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BotsRouteImport } from './routes/bots'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TablesTableIdRouteImport } from './routes/tables.$tableId'
import { Route as TablesTableIdGameRouteImport } from './routes/tables.$tableId.game'

const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsRoute = BotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesTableIdRoute = TablesTableIdRouteImport.update({
  id: '/$tableId',
  path: '/$tableId',
  getParentRoute: () => TablesRoute,
} as any)
const TablesTableIdGameRoute = TablesTableIdGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => TablesTableIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bots': typeof BotsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/tables': typeof TablesRouteWithChildren
  '/tables/$tableId': typeof TablesTableIdRouteWithChildren
  '/tables/$tableId/game': typeof TablesTableIdGameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bots': typeof BotsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/tables': typeof TablesRouteWithChildren
  '/tables/$tableId': typeof TablesTableIdRouteWithChildren
  '/tables/$tableId/game': typeof TablesTableIdGameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bots': typeof BotsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/tables': typeof TablesRouteWithChildren
  '/tables/$tableId': typeof TablesTableIdRouteWithChildren
  '/tables/$tableId/game': typeof TablesTableIdGameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bots'
    | '/login'
    | '/profile'
    | '/register'
    | '/tables'
    | '/tables/$tableId'
    | '/tables/$tableId/game'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bots'
    | '/login'
    | '/profile'
    | '/register'
    | '/tables'
    | '/tables/$tableId'
    | '/tables/$tableId/game'
  id:
    | '__root__'
    | '/'
    | '/bots'
    | '/login'
    | '/profile'
    | '/register'
    | '/tables'
    | '/tables/$tableId'
    | '/tables/$tableId/game'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BotsRoute: typeof BotsRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  TablesRoute: typeof TablesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots': {
      id: '/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof BotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables/$tableId': {
      id: '/tables/$tableId'
      path: '/$tableId'
      fullPath: '/tables/$tableId'
      preLoaderRoute: typeof TablesTableIdRouteImport
      parentRoute: typeof TablesRoute
    }
    '/tables/$tableId/game': {
      id: '/tables/$tableId/game'
      path: '/game'
      fullPath: '/tables/$tableId/game'
      preLoaderRoute: typeof TablesTableIdGameRouteImport
      parentRoute: typeof TablesTableIdRoute
    }
  }
}

interface TablesTableIdRouteChildren {
  TablesTableIdGameRoute: typeof TablesTableIdGameRoute
}

const TablesTableIdRouteChildren: TablesTableIdRouteChildren = {
  TablesTableIdGameRoute: TablesTableIdGameRoute,
}

const TablesTableIdRouteWithChildren = TablesTableIdRoute._addFileChildren(
  TablesTableIdRouteChildren,
)

interface TablesRouteChildren {
  TablesTableIdRoute: typeof TablesTableIdRouteWithChildren
}

const TablesRouteChildren: TablesRouteChildren = {
  TablesTableIdRoute: TablesTableIdRouteWithChildren,
}

const TablesRouteWithChildren =
  TablesRoute._addFileChildren(TablesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BotsRoute: BotsRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  TablesRoute: TablesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
